// <auto-generated />
using System;
using FinancialLifeInfrastructureData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialLifeInfrastructureData.Migrations
{
    [DbContext(typeof(FinancialLifeDbContext))]
    [Migration("20240223003402_PessoaContext")]
    partial class PessoaContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancialLifeDomain.Entities.Nucleo.Localizacao.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("FinancialLifeDomain.Entities.Nucleo.Pessoas.GeneroPessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("GeneroPessoa", (string)null);
                });

            modelBuilder.Entity("FinancialLifeDomain.Entities.Nucleo.Pessoas.PessoaFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("Cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("DataNascimento");

                    b.Property<int>("IdGeneroPessoa")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("IdGeneroPessoa")
                        .IsUnique();

                    b.ToTable("PessoaFisica", (string)null);
                });

            modelBuilder.Entity("FinancialLifeDomain.Entities.Nucleo.Pessoas.PessoaJuridica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar")
                        .HasColumnName("Cnpj");

                    b.Property<DateTime>("DataAberturaCnpj")
                        .HasColumnType("date")
                        .HasColumnName("DataAberturaCnpj");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar")
                        .HasColumnName("RazaoSocial");

                    b.HasKey("Id");

                    b.ToTable("PessoaJuridica", (string)null);
                });

            modelBuilder.Entity("FinancialLifeDomain.Entities.Nucleo.Pessoas.PessoaFisica", b =>
                {
                    b.HasOne("FinancialLifeDomain.Entities.Nucleo.Pessoas.GeneroPessoa", "GeneroPessoa")
                        .WithOne()
                        .HasForeignKey("FinancialLifeDomain.Entities.Nucleo.Pessoas.PessoaFisica", "IdGeneroPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneroPessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
